# **Data Transformation**

## **Dependecies**

In [71]:
import pandas as pd
import ast

## **Helper**

In [72]:
def parse_list(text):
    return ast.literal_eval(text)

## **Load CSV**

Load the csv fetched by the api

In [86]:
df = pd.read_csv("../data_collection/data/response_iati.csv")

print(df.info())   
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   iati_identifier                 1000 non-null   object
 1   title_narrative                 1000 non-null   object
 2   title_narrative_xml_lang        880 non-null    object
 3   reporting_org_narrative         1000 non-null   object
 4   description_narrative_xml_lang  880 non-null    object
 5   description_narrative           1000 non-null   object
 6   recipient_country_code          120 non-null    object
 7   recipient_region_code           880 non-null    object
 8   location_name_narrative         66 non-null     object
 9   activity_status_code            1000 non-null   int64
 10  document_link_url               201 non-null    object
 11  last_updated_datetime           1000 non-null   object
 12  activity_date_type              1000 non-null   object
 13  activity_date_iso_date          1000 non-null   object
 14  activity_date_narrative         0 non-null      float64
 15  sector_code                     1000 non-null   object
 16  sector_narrative                69 non-null     object
 17  sector_vocabulary               1000 non-null   object
 18  tag_code                        961 non-null    object
 19  tag_narrative                   0 non-null      float64
 20  tag_vocabulary                  961 non-null    object
 21  policy_marker_code              950 non-null    object
 22  policy_marker_narrative         0 non-null      float64
 23  policy_marker_code.1            950 non-null    object
 24  default_aid_type_code           995 non-null    object
dtypes: float64(3), int64(1), object(21)
memory usage: 195.4+ KB
None

,iati_identifier,title_narrative,title_narrative_xml_lang,reporting_org_narrative,description_narrative_xml_lang,description_narrative,recipient_country_code,recipient_region_code,location_name_narrative,activity_status_code,...,sector_code,sector_narrative,sector_vocabulary,tag_code,tag_narrative,tag_vocabulary,policy_marker_code,policy_marker_narrative,policy_marker_code.1,default_aid_type_code
0,DE-1-201226141-0,['--------------------------------------------...,"['en', 'de']",['Bundesministerium für wirtschaftliche Zusamm...,"['en', 'de', 'en', 'de']",['--------------------------------------------...,NaN,['998'],NaN,4,...,['91010'],NaN,['1'],['17'],NaN,['2'],NaN,NaN,NaN,['G01']
1,DE-1-201226166-0,['Förderung gemeindebasierter institutioneller...,"['de', 'en']",['Bundesministerium für wirtschaftliche Zusamm...,"['de', 'en', 'de', 'en']",['Förderung gemeindebasierter institutioneller...,NaN,['998'],NaN,4,...,['74010'],NaN,['1'],['11'],NaN,['2'],"['1', '2', '3', '5', '6', '7', '8', '9']",NaN,"['1', '2', '3', '5', '6', '7', '8', '9']",['C01']
2,DE-1-201228063-0,['Förderung des strategischen Quadrilogues von...,"['de', 'en']",['Bundesministerium für wirtschaftliche Zusamm...,"['de', 'en', 'de', 'en']",['Förderung des strategischen Quadrilogues von...,NaN,['998'],NaN,4,...,['43010'],NaN,['1'],"['11', '16']",NaN,"['2', '2']","['1', '2', '3', '5', '6', '7', '8', '9']",NaN,"['1', '2', '3', '5', '6', '7', '8', '9']",['C01']
3,DE-1-201228097-0,"['Internationale Akademie für Führungskräfte',...","['de', 'en']",['Bundesministerium für wirtschaftliche Zusamm...,"['de', 'en', 'de', 'en']","['Internationale Akademie für Führungskräfte',...",NaN,['998'],NaN,4,...,['15150'],NaN,['1'],"['11', '16']",NaN,"['2', '2']","['1', '2', '3', '5', '6', '7', '8', '9']",NaN,"['1', '2', '3', '5', '6', '7', '8', '9']",['B01']
4,DE-1-201228105-0,"['Domestic Programmes', 'Begleitende Projektma...","['en', 'de']",['Bundesministerium für wirtschaftliche Zusamm...,"['en', 'de', 'en', 'de']","['Domestic Programmes', 'Begleitende Projektma...",NaN,['998'],NaN,4,...,['15150'],NaN,['1'],"['16', '11']",NaN,"['2', '2']","['1', '2', '3', '5', '6', '7', '8', '9']",NaN,"['1', '2', '3', '5', '6', '7', '8', '9']",['B01']
5,DE-1-201228113-0,['Nachkontaktmaßnahmen für Fach- und Führungsk...,"['de', 'en']",['Bundesministerium für wirtschaftliche Zusamm...,"['de', 'en', 'de', 'en']",['Nachkontaktmaßnahmen für Fach- und Führungsk...,NaN,['998'],NaN,3,...,['15150'],NaN,['1'],"['11', '16']",NaN,"['2', '2']","['1', '2', '3', '5', '6', '7', '8', '9']",NaN,"['1', '2', '3', '5', '6', '7', '8', '9']",['B01']
6,DE-1-201228121-0,['Educational and training program for scienti...,"['en', 'de']",['Bundesministerium für wirtschaftliche Zusamm...,"['en', 'de', 'en', 'de']",['Educational and training program for scienti...,NaN,['998'],NaN,3,...,['15150'],NaN,['1'],"['10', '16', '5', '11']",NaN,"['2', '2', '2', '2']","['1', '2', '3', '5', '6', '7', '8', '9']",NaN,"['1', '2', '3', '5', '6', '7', '8', '9']",['B01']
7,DE-1-201228154-0,['Socio-political information and study tours ...,"['en', 'de']",['Bundesministerium für wirtschaftliche Zusamm...,"['en', 'de', 'en', 'de']",['Socio-political information and study tours ...,NaN,['998'],NaN,3,...,['15150'],NaN,['1'],"['11', '16']",NaN,"['2', '2']","['1', '2', '3', '5', '6', '7', '8', '9']",NaN,"['1', '2', '3', '5', '6', '7', '8', '9']",['B01']
8,DE-1-201228162-0,"['Vorbereitung von Auslandspersonal', 'Trainin...","['de', 'en']",['Bundesministerium für wirtschaftliche Zusamm...,"['de', 'en', 'de', 'en']","['Vorbereitung von Auslandspersonal', 'Trainin...",NaN,['998'],NaN,3,...,['15150'],NaN,['1'],"['5', '10', '11', '16']",NaN,"['2', '2', '2', '2']","['1', '2', '3', '5', '6', '7', '8', '9']",NaN,"['1', '2', '3', '5', '6', '7', '8', '9']",['B01']
9,DE-1-201228196-0,"['Dialogprogramm Brüssel', 'Dialogue Project B...","['de', 'en']",['Bundesministerium für wirtschaftliche Zusamm...,"['de', 'en', 'de', 'en']","['Dialogprogramm Brüssel', 'Dialogue Project B...",NaN,['998'],NaN,3,...,['15150'],NaN,['1'],"['16', '11']",NaN,"['2', '2']","['1', '2', '3', '5', '6', '7', '8', '9']",NaN,"['1', '2', '3', '5', '6', '7', '8', '9']",['C01']

## **Create new data frame**

In [74]:
trans_df = pd.DataFrame()

## **Transfrom columns**

### Transform ID

In [75]:
trans_df['id'] = df['iati_identifier']
trans_df.head(2)

                 id
0  DE-1-201226141-0
1  DE-1-201226166-0

### Transform title

It was decided to use the english title, if available, preferred to other languages. This was the case to enhance the comparability in the later stages of this analysis.

In [84]:
trans_df['title'] = df['title_narrative'].apply(lambda x: parse_list(x)[0])

# DECIDED TO USE ENGLISH TITLE PREFERRED TO OTHER LANGUAGES
for index, row in df.iterrows():
    try:
        # list of all available languages for the title
        lang_list = parse_list(row['title_narrative_xml_lang'])

        # if english is available as language find out the index and use the english version of the title
        if "en" in lang_list:
            en_idx = lang_list.index("en")
                
            trans_df.title[index] = parse_list(df.title_narrative[index])[en_idx]
    except:
        pass

trans_df.head(10)

,id,title,organization
0,DE-1-201226141-0,----------------------------------------------...,Bundesministerium für wirtschaftliche Zusammen...
1,DE-1-201226166-0,Support for community based institutional stru...,Bundesministerium für wirtschaftliche Zusammen...
2,DE-1-201228063-0,Promotion of an strategic Quadrilogue between ...,Bundesministerium für wirtschaftliche Zusammen...
3,DE-1-201228097-0,International Academy for Leadership,Bundesministerium für wirtschaftliche Zusammen...
4,DE-1-201228105-0,Domestic Programmes,Bundesministerium für wirtschaftliche Zusammen...
5,DE-1-201228113-0,Follow-up contacts for specialized and senior ...,Bundesministerium für wirtschaftliche Zusammen...
6,DE-1-201228121-0,Educational and training program for scientist...,Bundesministerium für wirtschaftliche Zusammen...
7,DE-1-201228154-0,Socio-political information and study tours of...,Bundesministerium für wirtschaftliche Zusammen...
8,DE-1-201228162-0,Training of FES personnel abroad,Bundesministerium für wirtschaftliche Zusammen...
9,DE-1-201228196-0,Dialogue Project Brussels,Bundesministerium für wirtschaftliche Zusammen...

### Transform organization

In [85]:
trans_df['organization'] = df['reporting_org_narrative'].apply(lambda x: parse_list(x)[0])
trans_df.head(2)

,id,title,organization
0,DE-1-201226141-0,----------------------------------------------...,Bundesministerium für wirtschaftliche Zusammen...
1,DE-1-201226166-0,Support for community based institutional stru...,Bundesministerium für wirtschaftliche Zusammen...

### Transform description

In [ ]:
trans_df['description'] = df['description_narrative'].apply(lambda x: parse_list(x)[0])

# DECIDED TO USE ENGLISH TITLE PREFERRED TO OTHER LANGUAGES
for index, row in df.iterrows():
    try:
        # list of all available languages for the title
        lang_list = parse_list(row['title_narrative_xml_lang'])

        # if english is available as language find out the index and use the english version of the title
        if "en" in lang_list:
            en_idx = lang_list.index("en")
                
            trans_df.title[index] = parse_list(df.title_narrative[index])[en_idx]
        else:
            pass
    except:
        pass

trans_df.head(10)